version: '3.8'

services:
  fra-digitization:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - ENVIRONMENT=production
      - OCR_PROVIDER=tesseract
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  streamlit-ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - API_URL=http://fra-digitization:8000
    command: streamlit run ui/streamlit_app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  data:
  models: